#!/bin/bash

set -eo pipefail

ENV_NAME=$1
VERSION=$2
LEG=$3

if [ -z "$ENV_NAME" ] || [ -z "$VERSION" ]; then
    echo "usage: $0 ENV_NAME VERSION [ LEG ] " >&2
    exit 1
fi

$(dirname $0)/platform-utils/get-base-info $ENV_NAME $VERSION $LEG\
    | $(dirname $0)/get-configuration \
    | $(dirname $0)/environment-export.py
